Repository aha-app/aha-services, pull requests merged in 2018-09, with the labels that each got.

#156 Remove Desk.com integration
  Gemfile
  docs/desk_dot_com.md
  lib/aha-services/version.rb
  lib/services/desk_dot_com.rb
  spec/services/bugzilla_spec.rb
Labels: enhancement

#159 Fixes APP-8846 - Update to use CircleCI 2.0
  .circleci/circle.yml
Labels: Needs Code Review

#157 Fixes APP-8835 - Handle the case where the checkitem is missing when …
  lib/services/trello/trello_checklist_resource.rb
Labels: Ready
